### ISSUE TITLE
How can I send track id when I use redeem method

### ISSUE THREAD

**Issue by zoriiz** [voucherifyio/voucherify-nodejs-sdk#104]
I try to use redeem method and add track id as a param without customer.

`client.redemptions.redeem(code, { track_id: 'string' })`

and I got this error

`{ code: 400,
message: 'Invalid RedemptionContext',
details: 'Unrecognized property \'tracking_id\'',
key: 'invalid_redemption_context',
toString: [Function] }`

Any idea?

**Comment by frakti** [comment]
Sorry for late response @zoriiz. You can find it in [README](https://github.com/voucherifyio/voucherify-nodejs-sdk#redeem-voucher):

```
client.redemptions.redeem(code, {customer: {source_id: 'string'}})
```
