### ISSUE TITLE
List campaigns

### ISSUE THREAD

**Issue by alexpchin** [voucherifyio/voucherify-nodejs-sdk#55]
Am I correct in thinking that there is no method to list campaigns: `https://api.voucherify.io/v1/campaigns`

**Comment by nitzo** [comment]
See PR #60

**Comment by frakti** [comment]
@alexpchin there is a method for listing campaigns in [v2017-04-05](https://docs.voucherify.io/v2017-04-05/reference).
We will release @nitzo PR soon.

**Comment by frakti** [comment]
@alexpchin @nitzo keep in mind if you want to use campaigns listing you need to specify that version when initializing the client:

```
const Voucherify = require('voucherify')

const client = Voucherify({
    applicationId: 'YOUR-APPLICATION-ID',
    clientSecretKey: 'YOUR-CLIENT-SECRET-KEY',
    apiVersion: 'v2017-04-20'
})
```
