### ISSUE TITLE
Distributions Calls Do Not Match API 

### ISSUE THREAD

**Issue by mcfullard** [voucherifyio/voucherify-nodejs-sdk#61]
According to your [API docs](https://docs.voucherify.io/reference#list-publications), your `distributions` endpoint should include calls for *List Publications*, *Create Export*, *Get Export*, and *Delete Export*, yet only the *Publish Voucher* call seems to be supported by the latest version of your SDK for Node.js. Do you plan on adding the remaining endpoints soon?

**Comment by tpindel** [comment]
@mcfullard Thanks for reaching out to us.

Actually, we didn't plan it for the nearest future, however, we can update plan. I believe it could be released at the end of this week.

If you need this earlier, I encourage to contribute by implementing a pull request through GitHub.

**Comment by mcfullard** [comment]
Hi @tpindel, thanks for replying so quickly. I've managed to use a few calls to your API to achieve the required result. Unfortunately I don't have time to try to do a pull request now.

**Comment by frakti** [comment]
@mcfullard FYI we have released `v2.10.0` of the sdk with support of all Distribution endpoints.

**Comment by mcfullard** [comment]
@frakti thanks! :+1:
