### ISSUE TITLE
utils.js validate discount methods: `!discount` check

### ISSUE THREAD

**Issue by olha-kurkaiedova** [voucherifyio/voucherify-nodejs-sdk#80]
```
function validatePercentDiscount (discount) {
  if (!discount || discount < 0 || discount > 100) {
    throw new Error('Invalid voucher, percent discount should be between 0-100.')
  }
}
```
Currently we have this kind of validation and according to this part `discount < 0` we can use `0` as discount (since this is not a strict comparison), this looks reasonable, but because of `!discount` (!0 == false -> says as that we did not pass the discount, but our discount is 0) the error from if condition will be thrown. Same thing for `validateAmountDiscount` and `validateUnitDiscount`.

Is there any chance that this behavior (checking for not passed discount) will be changed in nearest release?

**Comment by frakti** [comment]
@olha-kurkaiedova we've included your request in latest release `v2.17.0`.
