### ISSUE TITLE
Where is node.js API for validation rule assignment objects?

### ISSUE THREAD

**Issue by V1c70r** [voucherifyio/voucherify-nodejs-sdk#86]
There are some changes in Voucherify API
https://docs.voucherify.io/reference#create-validation-rules-assignment
https://docs.voucherify.io/reference#delete-validation-rules-assignment

But there are not any functions/methods/objects in voucherify-nodejs-sdk to work with validation rules assignments.

And time is running out "On 21st January 2019, we will switch off the old validation rule manager."...

**Comment by tpindel** [comment]
Hi @V1c70r ! Thanks for reaching out. Do you create and assign validation rules via API? For standard workflows those methods are not necessary, therefore, we decided to implement and release them later on.

**Comment by V1c70r** [comment]
Hi @tpindel ! Yes, I need to create/assign/get validation rules via API...

**Comment by frakti** [comment]
@V1c70r updated SDK including new methods is now released (`v2.21.0`).
Looking forward to your feedback. Thanks!

**Comment by V1c70r** [comment]
@frakti Thanks!
