### ISSUE TITLE
Track Custom Events - new version

### ISSUE THREAD

**Issue by bandraszyk** [voucherifyio/voucherify-nodejs-sdk#89]
Make sure that `Track Custom Event` method is supported: https://docs.voucherify.io/v2018-08-01/reference#create-custom-event

- `customer` and `event` are required
- `metadata` is optional
- `referral` is optional

**Comment by tpindel** [comment]
Moreover, add `loyalty` field.

**Comment by imvanzen** [comment]
@tpindel @bandraszyk @frakti I updated Event namespace and issued PR #96

**Comment by tpindel** [comment]
@bandraszyk I guess we can close the ticket, can't we?
