### ISSUE TITLE
Loyalties Program support

### ISSUE THREAD

**Issue by bandraszyk** [voucherifyio/voucherify-nodejs-sdk#93]
Add support for new methods related to Loyalty Programs.

Validation namespace:

- Validate Validation Rules: POST `/validation-rules/:rule-id/validation` - [Docs](http://docs.voucherify.io/v2018-08-01/reference?showHidden=b4b9a#validate-validation-rules)

Rewards namespace:

- List: GET `/rewards` - [Docs](http://docs.voucherify.io/v2018-08-01/reference?showHidden=b4b9a#list-rewards) 
- Create: POST `/rewards` - [Docs](http://docs.voucherify.io/v2018-08-01/reference?showHidden=b4b9a#create-reward)
- Get: GET `/rewards/:rewardId` - [Docs](http://docs.voucherify.io/v2018-08-01/reference?showHidden=b4b9a#get-reward)
- Update: PUT `/rewards/:rewardId` - [Docs](http://docs.voucherify.io/v2018-08-01/reference?showHidden=b4b9a#update-reward)
- Delete: DELETE `/rewards/:rewardId` - [Docs](http://docs.voucherify.io/v2018-08-01/reference?showHidden=b4b9a#delete-reward)
- List Assignments: GET `/rewards/:rewardId/assignments` - [Docs](http://docs.voucherify.io/v2018-08-01/reference?showHidden=b4b9a#list-reward-assignments)
- Create Assignment: POST `/rewards/:rewardId/assignments` - [Docs](http://docs.voucherify.io/v2018-08-01/reference?showHidden=b4b9a#create-reward-assignment)
- Update Assignment: PUT `/rewards/:rewardId/assignments/:assignmentId` - [Docs](http://docs.voucherify.io/v2018-08-01/reference?showHidden=b4b9a#update-reward-assignment)
- Delete Assignment: DELETE `/rewards/:rewardId/assignments/:assignmentId` - [Docs](http://docs.voucherify.io/v2018-08-01/reference?showHidden=b4b9a#delete-reward-assignment)

Loyalties namespace:

- List: GET `/loyalties` - [Docs](http://docs.voucherify.io/v2018-08-01/reference?showHidden=b4b9a#list-loyalty-programs)
- Create: POST `/loyalties` - [Docs](http://docs.voucherify.io/v2018-08-01/reference?showHidden=b4b9a#create-loyalty-program)
- Get: GET `/loyalties/:campaignId` - [Docs](http://docs.voucherify.io/v2018-08-01/reference?showHidden=b4b9a#get-loyalty-program)
- Update: PUT `/loyalties/:campaignId` - [Docs](http://docs.voucherify.io/v2018-08-01/reference?showHidden=b4b9a#update-loyalty-program)
- Delete: DELETE `/loyalties/:campaignId` - [Docs](http://docs.voucherify.io/v2018-08-01/reference?showHidden=b4b9a#delete-loyalty-program)
- List Reward Assignments: GET `/loyalties/:campaignId/rewards` - [Docs](http://docs.voucherify.io/v2018-08-01/reference?showHidden=b4b9a#list-reward-assignments-1)
- Create Reward Assignment: POST `/loyalties/:campaignId/rewards` - [Docs](http://docs.voucherify.io/v2018-08-01/reference?showHidden=b4b9a#create-reward-assignment-1)
- Update Reward Assignment: PUT `/loyalties/:campaignId/rewards/:assignmentId` - [Docs](http://docs.voucherify.io/v2018-08-01/reference?showHidden=b4b9a#update-reward-assignment-1)
- Delete Reward Assignment: DELETE `/loyalties/:campaignId/rewards/:assignmentId` - [Docs](http://docs.voucherify.io/v2018-08-01/reference?showHidden=b4b9a#delete-reward-assignment-1)
- List Earning Rules: GET `/loyalties/{campaignId}/earning-rules` - [Docs](http://docs.voucherify.io/v2018-08-01/reference?showHidden=b4b9a#list-earning-rules)
- Create Earning Rules: POST `/loyalties/:campaignId/earning-rules` - [Docs](http://docs.voucherify.io/v2018-08-01/reference?showHidden=b4b9a#create-earning-rule)
- Update Earning Rules: PUT `/loyalties/:campaignId/earning-rules/:earningRuleId` - [Docs](http://docs.voucherify.io/v2018-08-01/reference?showHidden=b4b9a#update-earning-rule)
- Delete Earning Rules: DELETE `/loyalties/:campaignId/earning-rules/:earningRuleId` - [Docs](http://docs.voucherify.io/v2018-08-01/reference?showHidden=b4b9a#delete-earning-rule)
- List Members: GET `/loyalties/:campaignId/members` - [Docs](http://docs.voucherify.io/v2018-08-01/reference?showHidden=b4b9a#list-members)
- Add Member: POST `/loyalties/:campaignId/members` - [Docs](http://docs.voucherify.io/v2018-08-01/reference?showHidden=b4b9a#create-member)
- Get Member: GET `/loyalties/:campaignId/members/:memberId` - [Docs](http://docs.voucherify.io/v2018-08-01/reference?showHidden=b4b9a#get-member)
- Add Points: POST `/loyalties/:campaignId/members/:memberId/balance` - [Docs](http://docs.voucherify.io/v2018-08-01/reference?showHidden=b4b9a#add-loyalty-card-balance)
- Redeem Reward: POST `/loyalties/:campaignId/members/:memberId/redemption` - [Docs](http://docs.voucherify.io/v2018-08-01/reference?showHidden=b4b9a#redeem-loyalty-card)

**Comment by bandraszyk** [comment]
Redemption:

- Redeem Voucher, added `reward` property: [Docs](https://docs.voucherify.io/reference#redeem-voucher)
- Redeem Voucher (client), added `reward` property [Docs](https://docs.voucherify.io/reference#redeem-voucher-client-side)

Events:

- Track Event, added `loyalty` property [Docs](https://docs.voucherify.io/reference#create-custom-event)
- Track Event (client), added `loyalty` property [Docs](https://docs.voucherify.io/reference#track-custom-event-client-side)

**Comment by imvanzen** [comment]
@bandraszyk I created a PR which adds new methods to the SDK
https://github.com/voucherifyio/voucherify-nodejs-sdk/pull/95

@frakti A review will be very useful. Particularly noteworthy are the methods for redeeming rewards and adding points in the `loyalty` namespace.

**Comment by tpindel** [comment]
@bandraszyk I guess we can close the ticket, can't we?
